import React from 'react';
import { Image } from 'expo-image';
import { Modal, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { X } from 'lucide-react-native';
import { theme } from '../../../core/theme';

type Photo = { id: string; url: string; type: 'CHECKIN' | 'CHECKOUT'; categorie?: string };
export const BookingEtatLieuxGalleryModal: React.FC<{ visible: boolean; photos: Photo[]; onClose: () => void }> = ({ visible, photos, onClose }) => <Modal visible={visible} animationType="slide" onRequestClose={onClose}><SafeAreaView style={styles.safe}><View style={styles.header}><View><Text style={styles.title}>État des lieux</Text><Text style={styles.subtitle}>{photos.length} photo{photos.length > 1 ? 's' : ''} disponible{photos.length > 1 ? 's' : ''}</Text></View><TouchableOpacity onPress={onClose} style={styles.close}><X size={19} color="#FFFFFF" /></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}>{(['CHECKIN', 'CHECKOUT'] as const).map((type) => { const group = photos.filter((photo) => photo.type === type); return group.length ? <View key={type} style={styles.group}><Text style={styles.groupTitle}>{type === 'CHECKIN' ? 'PRISE EN CHARGE' : 'RESTITUTION'}</Text><View style={styles.grid}>{group.map((photo) => <View key={photo.id} style={styles.photo}><Image source={{ uri: photo.url }} contentFit="cover" style={styles.image} /><Text style={styles.caption}>{photo.categorie || 'Photo'}</Text></View>)}</View></View> : null; })}</ScrollView></SafeAreaView></Modal>;
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#041912' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 18, paddingVertical: 14, borderBottomWidth: 1, borderColor: 'rgba(255,255,255,.12)' }, title: { color: '#FFFFFF', fontFamily: theme.typography.fontFamily.displaySemiBold, fontSize: 20 }, subtitle: { color: '#A7F3D0', fontFamily: theme.typography.fontFamily.regular, fontSize: 12, marginTop: 2 }, close: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.12)' }, content: { padding: 16, gap: 22 }, group: { gap: 9 }, groupTitle: { color: '#A7F3D0', fontFamily: theme.typography.fontFamily.bold, fontSize: 10, letterSpacing: .9 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, photo: { width: '48%', aspectRatio: .88, overflow: 'hidden', borderRadius: 12, backgroundColor: '#1E293B' }, image: { width: '100%', height: '100%' }, caption: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: 7, color: '#FFFFFF', backgroundColor: 'rgba(0,0,0,.55)', fontFamily: theme.typography.fontFamily.semiBold, fontSize: 10 } });
