import React from 'react';
import { Modal, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { CheckCircle2, CircleDollarSign, ShieldCheck, X } from 'lucide-react-native';
import { theme } from '../../../core/theme';

export const BookingLifecycleRulesModal: React.FC<{ visible: boolean; modePaiement?: string; onClose: () => void }> = ({ visible, modePaiement, onClose }) => {
  const isDeposit = modePaiement === 'ACOMPTE_SOLDE_CHECKIN';
  return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><Text style={styles.title}>Règles de votre location</Text><TouchableOpacity onPress={onClose} style={styles.close}><X size={18} color="#334155" /></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}><Rule number="1" title="Réservation confirmée" text="Les coordonnées de l’hôte se déverrouillent 24 h avant la prise en charge, puis restent visibles pendant la location." /><Rule number="2" title="État des lieux" text="L’hôte dépose les photos et confirme le check-in. Vous inspectez le véhicule avant de valider votre propre confirmation." /><Rule number="3" title="Double validation" text="La location passe en cours uniquement après les validations de l’hôte et du locataire. En cas de non-conformité, refusez le véhicule avant de confirmer." /><Rule number="4" title={isDeposit ? 'Acompte et solde' : 'Paiement sécurisé'} text={isDeposit ? 'L’acompte est réglé en ligne. Le solde est confirmé par l’hôte lors de la remise des clés.' : 'Le règlement en ligne est lié à cette réservation et reste tracé par AutoLoc.'} /><View style={styles.notice}><ShieldCheck size={17} color="#047857" /><Text style={styles.noticeText}>Les conditions applicables à une annulation sont calculées par le serveur au moment de votre demande.</Text></View></ScrollView><SafeAreaView style={styles.footer}><TouchableOpacity onPress={onClose} style={styles.button}><Text style={styles.buttonText}>J’ai compris</Text></TouchableOpacity></SafeAreaView></View></View></Modal>;
};
const Rule = ({ number, title, text }: { number: string; title: string; text: string }) => <View style={styles.rule}><View style={styles.number}><Text style={styles.numberText}>{number}</Text></View><View style={styles.ruleCopy}><Text style={styles.ruleTitle}>{title}</Text><Text style={styles.ruleText}>{text}</Text></View></View>;
const styles = StyleSheet.create({ backdrop: { flex: 1, backgroundColor: 'rgba(4,25,18,.62)', justifyContent: 'flex-end' }, sheet: { maxHeight: '88%', borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: '#FFFFFF' }, handle: { alignSelf: 'center', width: 40, height: 4, borderRadius: 3, backgroundColor: '#CBD5E1', marginTop: 10 }, header: { padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderColor: '#E2E8F0' }, title: { color: '#072A20', fontFamily: theme.typography.fontFamily.displaySemiBold, fontSize: 20 }, close: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center' }, content: { padding: 20, gap: 18 }, rule: { flexDirection: 'row', gap: 11 }, number: { width: 27, height: 27, borderRadius: 14, backgroundColor: '#ECFDF5', alignItems: 'center', justifyContent: 'center' }, numberText: { color: '#047857', fontFamily: theme.typography.fontFamily.bold, fontSize: 12 }, ruleCopy: { flex: 1 }, ruleTitle: { color: '#072A20', fontFamily: theme.typography.fontFamily.semiBold, fontSize: 14 }, ruleText: { color: '#64748B', fontFamily: theme.typography.fontFamily.regular, fontSize: 12, lineHeight: 18, marginTop: 3 }, notice: { flexDirection: 'row', gap: 9, padding: 12, borderRadius: 13, backgroundColor: '#ECFDF5' }, noticeText: { flex: 1, color: '#065F46', fontFamily: theme.typography.fontFamily.medium, fontSize: 12, lineHeight: 17 }, footer: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 8, borderTopWidth: 1, borderColor: '#E2E8F0' }, button: { minHeight: 48, borderRadius: 24, backgroundColor: '#072A20', alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#FFFFFF', fontFamily: theme.typography.fontFamily.bold, fontSize: 14 } });
