import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { AlertTriangle, X } from 'lucide-react-native';
import { formatCurrency } from '@autoloc/shared';
import { apiClient } from '../../../core/api/apiClient';
import { theme } from '../../../core/theme';

type Quote = { canCancel: boolean; refundPercentage: number; refundAmount: string; commissionRetained: string; warnings: string[] };
export const BookingCancellationPreviewModal: React.FC<{ visible: boolean; reservationId: string; submitting: boolean; onClose: () => void; onConfirm: (reason: string) => Promise<void> }> = ({ visible, reservationId, submitting, onClose, onConfirm }) => {
  const [quote, setQuote] = useState<Quote | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [reason, setReason] = useState('');
  useEffect(() => { if (!visible) return; setReason(''); setQuote(null); setError(null); setLoading(true); void apiClient.get<Quote>(`/reservations/${reservationId}/cancellation-quote`).then((r) => setQuote(r.data)).catch((e) => setError(e?.response?.data?.message || 'Impossible de calculer le remboursement.')).finally(() => setLoading(false)); }, [reservationId, visible]);
  const submit = async () => { if (reason.trim().length < 5) return setError('Le motif doit contenir au moins 5 caractères.'); await onConfirm(reason.trim()); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><Text style={styles.title}>Annuler la réservation</Text><TouchableOpacity onPress={onClose}><X size={20} color="#334155" /></TouchableOpacity></View>{loading ? <View style={styles.loader}><ActivityIndicator color={theme.colors.brand.main} /></View> : <View style={styles.content}>{quote ? <View style={styles.quote}><Text style={styles.micro}>REMBOURSEMENT ESTIMÉ</Text><Text style={styles.amount}>{formatCurrency(Number(quote.refundAmount))}</Text><Text style={styles.percent}>{quote.refundPercentage}% selon la politique AutoLoc</Text>{quote.warnings.map((warning) => <Text key={warning} style={styles.warning}>• {warning}</Text>)}</View> : null}{error ? <Text style={styles.error}>{error}</Text> : null}<TextInput value={reason} onChangeText={setReason} style={styles.input} multiline placeholder="Motif d’annulation (obligatoire)" /><Text style={styles.hint}>Le montant définitif est recalculé par le serveur à la confirmation.</Text><SafeAreaView><TouchableOpacity disabled={submitting || !quote?.canCancel} onPress={submit} style={styles.button}><Text style={styles.buttonText}>{submitting ? 'Annulation…' : 'Confirmer l’annulation'}</Text></TouchableOpacity></SafeAreaView></View>}</View></View></Modal>;
};
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(4,25,18,.62)' }, sheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: '#FFFFFF' }, header: { flexDirection: 'row', justifyContent: 'space-between', padding: 20, borderBottomWidth: 1, borderColor: '#E2E8F0' }, title: { color: '#072A20', fontFamily: theme.typography.fontFamily.displaySemiBold, fontSize: 19 }, loader: { padding: 42 }, content: { padding: 20, gap: 13 }, quote: { padding: 16, borderRadius: 14, backgroundColor: '#FEF2F2', borderWidth: 1, borderColor: '#FECACA' }, micro: { color: '#991B1B', fontFamily: theme.typography.fontFamily.bold, fontSize: 10, letterSpacing: .7 }, amount: { color: '#7F1D1D', fontFamily: theme.typography.fontFamily.displaySemiBold, fontSize: 26, marginTop: 4 }, percent: { color: '#991B1B', fontFamily: theme.typography.fontFamily.medium, fontSize: 12 }, warning: { color: '#991B1B', fontFamily: theme.typography.fontFamily.regular, fontSize: 11, marginTop: 7 }, error: { color: '#B91C1C', fontFamily: theme.typography.fontFamily.medium, fontSize: 12 }, input: { minHeight: 70, borderRadius: 12, borderWidth: 1, borderColor: '#CBD5E1', padding: 12, textAlignVertical: 'top', fontFamily: theme.typography.fontFamily.regular }, hint: { color: '#64748B', fontFamily: theme.typography.fontFamily.regular, fontSize: 11 }, button: { minHeight: 48, borderRadius: 24, backgroundColor: '#B91C1C', alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#FFFFFF', fontFamily: theme.typography.fontFamily.bold, fontSize: 13 } });
