import React, { useState } from 'react';
import { Alert, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Star } from 'lucide-react-native';
import { apiClient } from '../../../core/api/apiClient';
import { theme } from '../../../core/theme';

export const BookingCompletionPanel: React.FC<{ reservationId: string; existingReview?: { note: number; commentaire?: string } }> = ({ reservationId, existingReview }) => {
  const [rating, setRating] = useState(existingReview?.note || 0); const [comment, setComment] = useState(existingReview?.commentaire || ''); const [saving, setSaving] = useState(false); const [done, setDone] = useState(Boolean(existingReview));
  const submit = async () => { if (!rating) return Alert.alert('Note requise', 'Choisissez une note de 1 à 5.'); try { setSaving(true); await apiClient.post('/reviews', { reservationId, note: rating, commentaire: comment.trim() || undefined }); setDone(true); } catch (e: any) { Alert.alert('Avis non envoyé', e?.response?.data?.message || 'Réessayez plus tard.'); } finally { setSaving(false); } };
  return <View style={styles.card}><Text style={styles.title}>Location terminée</Text><Text style={styles.text}>{done ? 'Merci pour votre avis.' : 'Partagez votre expérience avec cet hôte.'}</Text><View style={styles.stars}>{[1,2,3,4,5].map((value) => <TouchableOpacity key={value} disabled={done} onPress={() => setRating(value)}><Star size={26} color="#F59E0B" fill={value <= rating ? '#F59E0B' : 'transparent'} /></TouchableOpacity>)}</View>{!done ? <><TextInput value={comment} onChangeText={setComment} placeholder="Votre commentaire (facultatif)" style={styles.input} multiline /><TouchableOpacity disabled={saving} onPress={submit} style={styles.button}><Text style={styles.buttonText}>{saving ? 'Envoi…' : 'Publier mon avis'}</Text></TouchableOpacity></> : null}</View>;
};
const styles = StyleSheet.create({ card: { padding: 16, gap: 10, borderRadius: 18, backgroundColor: '#FFFBEB', borderWidth: 1, borderColor: '#FDE68A' }, title: { color: '#78350F', fontFamily: theme.typography.fontFamily.displaySemiBold, fontSize: 16 }, text: { color: '#92400E', fontFamily: theme.typography.fontFamily.regular, fontSize: 12 }, stars: { flexDirection: 'row', gap: 7 }, input: { minHeight: 70, borderWidth: 1, borderColor: '#FCD34D', borderRadius: 12, padding: 10, textAlignVertical: 'top' }, button: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 22, backgroundColor: '#92400E' }, buttonText: { color: '#FFFFFF', fontFamily: theme.typography.fontFamily.bold, fontSize: 13 } });
