import React, { useState } from 'react';
import * as ImagePicker from 'expo-image-picker';
import { ActivityIndicator, Alert, Image, Modal, SafeAreaView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Camera, CheckCircle2, ImagePlus, X } from 'lucide-react-native';
import { apiClient } from '../../../core/api/apiClient';
import { theme } from '../../../core/theme';

const REASONS = ['NON_CONFORMITE', 'DEGATS', 'ACCES_IMPOSSIBLE', 'AUTRE'];
export const RefuseVehicleEvidenceModal: React.FC<{ visible: boolean; reservationId: string; submitting: boolean; onClose: () => void; onSubmit: (reason: string, comment: string) => Promise<boolean> }> = ({ visible, reservationId, submitting, onClose, onSubmit }) => {
  const [motif, setMotif] = useState('NON_CONFORMITE'); const [comment, setComment] = useState(''); const [imageUri, setImageUri] = useState<string | null>(null); const [uploading, setUploading] = useState(false);
  const selectPhoto = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('Autorisation requise', 'Autorisez l’accès aux photos pour joindre une preuve.'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: .8 }); if (!result.canceled) setImageUri(result.assets[0].uri); };
  const submit = async () => { if (comment.trim().length < 15) return Alert.alert('Description insuffisante', 'Décrivez le problème en au moins 15 caractères.'); if (!imageUri) return Alert.alert('Preuve requise', 'Ajoutez au moins une photo avant de signaler la non-conformité.'); try { setUploading(true); const form = new FormData(); form.append('file', { uri: imageUri, name: 'preuve-non-conformite.jpg', type: 'image/jpeg' } as any); await apiClient.post(`/reservations/${reservationId}/photos-etat?type=CHECKIN&categorie=AUTRE`, form, { headers: { 'Content-Type': 'multipart/form-data' } }); const ok = await onSubmit(motif, comment.trim()); if (ok) { setComment(''); setImageUri(null); onClose(); } } catch (e: any) { Alert.alert('Envoi impossible', e?.response?.data?.message || 'La preuve n’a pas pu être envoyée.'); } finally { setUploading(false); } };
  return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><Text style={styles.title}>Véhicule non conforme</Text><TouchableOpacity onPress={onClose}><X size={20} color="#334155" /></TouchableOpacity></View><View style={styles.content}><Text style={styles.intro}>Votre signalement ouvre un litige. Ajoutez une preuve avant de refuser la prise en charge.</Text><Text style={styles.label}>MOTIF</Text><View style={styles.chips}>{REASONS.map((reason) => <TouchableOpacity key={reason} onPress={() => setMotif(reason)} style={[styles.chip, motif === reason && styles.chipActive]}><Text style={[styles.chipText, motif === reason && styles.chipTextActive]}>{reason.replace('_', ' ')}</Text></TouchableOpacity>)}</View><TextInput style={styles.input} multiline value={comment} onChangeText={setComment} placeholder="Décrivez précisément le problème constaté…" /><TouchableOpacity onPress={selectPhoto} style={styles.evidence}>{imageUri ? <Image source={{ uri: imageUri }} style={styles.preview} /> : <ImagePlus size={22} color={theme.colors.brand.main} />}<View style={styles.evidenceCopy}><Text style={styles.evidenceTitle}>{imageUri ? 'Preuve ajoutée' : 'Ajouter une photo de preuve'}</Text><Text style={styles.evidenceText}>Obligatoire pour envoyer le signalement</Text></View></TouchableOpacity><SafeAreaView><TouchableOpacity disabled={submitting || uploading} onPress={submit} style={styles.button}>{submitting || uploading ? <ActivityIndicator color="#FFFFFF" /> : <><Camera size={16} color="#FFFFFF" /><Text style={styles.buttonText}>Envoyer le signalement</Text></>}</TouchableOpacity></SafeAreaView></View></View></View></Modal>;
};
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(4,25,18,.65)' }, sheet: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24 }, header: { padding: 20, flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderColor: '#E2E8F0' }, title: { color: '#7F1D1D', fontFamily: theme.typography.fontFamily.displaySemiBold, fontSize: 19 }, content: { padding: 20, gap: 13 }, intro: { color: '#64748B', fontFamily: theme.typography.fontFamily.regular, fontSize: 12, lineHeight: 18 }, label: { color: '#64748B', fontFamily: theme.typography.fontFamily.bold, fontSize: 10, letterSpacing: .7 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { paddingHorizontal: 10, paddingVertical: 8, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 16 }, chipActive: { backgroundColor: '#7F1D1D', borderColor: '#7F1D1D' }, chipText: { color: '#475569', fontFamily: theme.typography.fontFamily.semiBold, fontSize: 10 }, chipTextActive: { color: '#FFFFFF' }, input: { minHeight: 78, borderRadius: 12, borderWidth: 1, borderColor: '#CBD5E1', padding: 12, textAlignVertical: 'top', fontFamily: theme.typography.fontFamily.regular }, evidence: { minHeight: 72, borderRadius: 12, padding: 10, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderStyle: 'dashed', borderColor: '#86EFAC', backgroundColor: '#F0FDF4' }, preview: { width: 50, height: 50, borderRadius: 8 }, evidenceCopy: { flex: 1 }, evidenceTitle: { color: '#166534', fontFamily: theme.typography.fontFamily.semiBold, fontSize: 12 }, evidenceText: { color: '#4B5563', fontFamily: theme.typography.fontFamily.regular, fontSize: 10, marginTop: 2 }, button: { minHeight: 49, borderRadius: 25, backgroundColor: '#B91C1C', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 }, buttonText: { color: '#FFFFFF', fontFamily: theme.typography.fontFamily.bold, fontSize: 13 } });
