import { Vehicle } from "../types/vehicle.types";

export const MOCK_SENEGAL_VEHICLES: Vehicle[] = [
  {
    id: "v-mock-1",
    marque: "Toyota",
    modele: "Land Cruiser Prado V8",
    annee: 2023,
    type: "FOUR_X_FOUR",
    prixParJour: 75000,
    ville: "Dakar",
    adresse: "Almadies, Route des Almadies",
    latitude: 14.7452,
    longitude: -17.5186,
    note: 4.95,
    totalAvis: 48,
    statut: "DISPONIBLE",
    totalLocations: 62,
    carburant: "DIESEL",
    transmission: "AUTOMATIQUE",
    nombrePlaces: 7,
    joursMinimum: 2,
    ageMinimum: 23,
    zoneConduite: "Tout le Sénégal",
    assurance: "Tous Risques AXA",
    proposeLivraisonDakar: true,
    fraisLivraisonDakar: 0,
    proposeLivraisonAibd: true,
    fraisLivraisonAibd: 15000,
    isFeatured: true,
    photoUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1200&auto=format&fit=crop",
    photos: [
      { id: "p1", url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=1200&auto=format&fit=crop" },
      { id: "p2", url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1200&auto=format&fit=crop" },
      { id: "p3", url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop" },
    ],
    description: "Le baroudeur de luxe idéal pour explorer Dakar et les pistes du Sénégal. Climatisation tri-zone, sièges cuir et chauffeur possible sur demande.",
    proprietaire: {
      id: "prop-1",
      prenom: "Mamadou",
      nom: "Diallo",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=300&auto=format&fit=crop",
      noteProprietaire: 4.98,
      totalAvis: 89,
    },
  },
  {
    id: "v-mock-2",
    marque: "Hyundai",
    modele: "Tucson All-Black",
    annee: 2022,
    type: "SUV",
    prixParJour: 35000,
    ville: "Dakar",
    adresse: "Ngor Virage, Dakar",
    latitude: 14.7523,
    longitude: -17.5098,
    note: 4.88,
    totalAvis: 31,
    statut: "DISPONIBLE",
    totalLocations: 41,
    carburant: "ESSENCE",
    transmission: "AUTOMATIQUE",
    nombrePlaces: 5,
    joursMinimum: 1,
    ageMinimum: 21,
    zoneConduite: "Dakar & Région de Thiès",
    assurance: "Tous Risques NSIA",
    proposeLivraisonDakar: true,
    fraisLivraisonDakar: 5000,
    proposeLivraisonAibd: true,
    fraisLivraisonAibd: 12000,
    isFeatured: true,
    photoUrl: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1200&auto=format&fit=crop",
    photos: [
      { id: "p4", url: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=1200&auto=format&fit=crop" },
      { id: "p5", url: "https://images.unsplash.com/photo-1502877338535-766e1452684a?q=80&w=1200&auto=format&fit=crop" },
    ],
    description: "SUV urbain moderne et très économique. Écran tactile Apple CarPlay / Android Auto, caméra 360 et toit panoramique.",
    proprietaire: {
      id: "prop-2",
      prenom: "Aïssatou",
      nom: "Ndiaye",
      avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=300&auto=format&fit=crop",
      noteProprietaire: 4.92,
      totalAvis: 56,
    },
  },
  {
    id: "v-mock-3",
    marque: "Range Rover",
    modele: "Evoque HSE Dynamic",
    annee: 2023,
    type: "LUXE",
    prixParJour: 90000,
    ville: "Dakar",
    adresse: "Plateau, Avenue Léopold Sédar Senghor",
    latitude: 14.6675,
    longitude: -17.4332,
    note: 4.98,
    totalAvis: 19,
    statut: "DISPONIBLE",
    totalLocations: 28,
    carburant: "ESSENCE",
    transmission: "AUTOMATIQUE",
    nombrePlaces: 5,
    joursMinimum: 2,
    ageMinimum: 25,
    zoneConduite: "Dakar & Littoral",
    assurance: "Tous Risques Premium",
    proposeLivraisonDakar: true,
    fraisLivraisonDakar: 0,
    proposeLivraisonAibd: true,
    fraisLivraisonAibd: 10000,
    isFeatured: true,
    photoUrl: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=1200&auto=format&fit=crop",
    photos: [
      { id: "p6", url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=1200&auto=format&fit=crop" },
      { id: "p7", url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1200&auto=format&fit=crop" },
    ],
    description: "Élégance ultime pour vos déplacements d'affaires ou mariages à Dakar. Système audio Meridian 825W, intérieur cuir Oyster.",
    proprietaire: {
      id: "prop-3",
      prenom: "Cheikh",
      nom: "Sow",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=300&auto=format&fit=crop",
      noteProprietaire: 5.0,
      totalAvis: 34,
    },
  },
  {
    id: "v-mock-4",
    marque: "Suzuki",
    modele: "Swift GLX Automatique",
    annee: 2023,
    type: "CITADINE",
    prixParJour: 22000,
    ville: "Dakar",
    adresse: "Mermoz, Ancienne Piste",
    latitude: 14.7088,
    longitude: -17.4725,
    note: 4.82,
    totalAvis: 54,
    statut: "DISPONIBLE",
    totalLocations: 76,
    carburant: "ESSENCE",
    transmission: "AUTOMATIQUE",
    nombrePlaces: 5,
    joursMinimum: 1,
    ageMinimum: 21,
    zoneConduite: "Dakar intra-muros",
    assurance: "Tous Risques",
    proposeLivraisonDakar: true,
    fraisLivraisonDakar: 3000,
    isFeatured: false,
    photoUrl: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1200&auto=format&fit=crop",
    photos: [
      { id: "p8", url: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?q=80&w=1200&auto=format&fit=crop" },
    ],
    description: "Citadine ultra maniable, consommation réduite (5L/100km). Idéale pour se garer facilement au Plateau ou à Fann.",
    proprietaire: {
      id: "prop-4",
      prenom: "Fatou",
      nom: "Ba",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=300&auto=format&fit=crop",
      noteProprietaire: 4.89,
      totalAvis: 98,
    },
  },
  {
    id: "v-mock-5",
    marque: "Mitsubishi",
    modele: "Pajero Sport 4x4",
    annee: 2021,
    type: "FOUR_X_FOUR",
    prixParJour: 55000,
    ville: "Saly",
    adresse: "Station Saly Portudal",
    latitude: 14.4442,
    longitude: -17.0211,
    note: 4.90,
    totalAvis: 27,
    statut: "DISPONIBLE",
    totalLocations: 38,
    carburant: "DIESEL",
    transmission: "AUTOMATIQUE",
    nombrePlaces: 7,
    joursMinimum: 2,
    ageMinimum: 23,
    zoneConduite: "Petite Côte & Sine Saloum",
    assurance: "Tous Risques",
    proposeLivraisonDakar: true,
    fraisLivraisonDakar: 10000,
    proposeLivraisonAibd: true,
    fraisLivraisonAibd: 5000,
    isFeatured: true,
    photoUrl: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?q=80&w=1200&auto=format&fit=crop",
    photos: [
      { id: "p9", url: "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?q=80&w=1200&auto=format&fit=crop" },
    ],
    description: "Parfait pour vos escapades le week-end à Saly, Somone et la réserve de Bandia. 7 vraies places et coffre spacieux.",
    proprietaire: {
      id: "prop-5",
      prenom: "Ousmane",
      nom: "Faye",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop",
      noteProprietaire: 4.95,
      totalAvis: 44,
    },
  },
  {
    id: "v-mock-6",
    marque: "Peugeot",
    modele: "3008 GT Line",
    annee: 2022,
    type: "SUV",
    prixParJour: 40000,
    ville: "Dakar",
    adresse: "Sacré-Cœur 3, Dakar",
    latitude: 14.7194,
    longitude: -17.4647,
    note: 4.91,
    totalAvis: 39,
    statut: "DISPONIBLE",
    totalLocations: 51,
    carburant: "DIESEL",
    transmission: "AUTOMATIQUE",
    nombrePlaces: 5,
    joursMinimum: 1,
    ageMinimum: 22,
    zoneConduite: "Sénégal",
    assurance: "Tous Risques",
    proposeLivraisonDakar: true,
    fraisLivraisonDakar: 0,
    isFeatured: true,
    photoUrl: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?q=80&w=1200&auto=format&fit=crop",
    photos: [
      { id: "p10", url: "https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?q=80&w=1200&auto=format&fit=crop" },
    ],
    description: "Design i-Cockpit futuriste, feux Full LED, très grand confort de conduite pour vos longs trajets vers Thiès et Mbour.",
    proprietaire: {
      id: "prop-6",
      prenom: "Khadija",
      nom: "Sy",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=300&auto=format&fit=crop",
      noteProprietaire: 4.97,
      totalAvis: 67,
    },
  }
];
